import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";
import NavComponent from "@/components/nav/NavComponent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const interFont = Inter({
  subsets: ["latin"],
  weight: ["400", "600", "700", "900"],
  variable: "--my-font-family",
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={`${interFont.variable} bg-bgLight `}>
        <SessionProvider session={session}>
          <NavComponent />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
